// <auto-generated />
namespace SocialServicesManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditDataassembly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditDataassembly));
        
        string IMigrationMetadata.Id
        {
            get { return "201706042037207_Edit Data assembly"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
