// <auto-generated />
namespace SocialServicesManager.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdditionalDbSets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdditionalDbSets));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041059192_Additional DbSets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
