// <auto-generated />
namespace SocialServicesManager.Data.SqliteMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addconstraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addconstraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201706101631536_Add constraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
